spring:
  datasource:
    url: jdbc:postgresql://localhost:6789/gym
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
